fix so require works
Was creating the following message when running code previously

pluralsight-4ac39e20:~/environment/app (master) $ node create-and-deploy.js
file:///home/ec2-user/environment/app/create-and-deploy.js:1
const aws = require('./lib/aws.js');
            ^

ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/home/ec2-user/environment/app/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/ec2-user/environment/app/create-and-deploy.js:1:13
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
    at async handleMainPromise (node:internal/modules/run_main:63:12)